# Generated by Django 6.1.2 on 2026-10-07 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('party', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.PositiveSmallIntegerField()),
                ('bill_type', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('origin_chamber', models.CharField(blank=True, max_length=20)),
                ('policy_area', models.CharField(blank=True, max_length=200)),
                ('introduced_date', models.DateField(blank=True, null=True)),
                ('latest_action_date', models.DateField(blank=True, null=True)),
                ('latest_action_text', models.TextField(blank=True)),
                ('api_update_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_bills', to='bills.member')),
            ],
            options={
                'ordering': ['-latest_action_date'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('text', models.TextField()),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('action_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bills.bill')),
            ],
            options={
                'ordering': ['-action_date'],
                'constraints': [models.UniqueConstraint(fields=('bill', 'action_date', 'text'), name='unique_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('congress', 'bill_type', 'number'), name='unique_bill'),
        ),
    ]
