# Generated by Django 6.1.2 on 2026-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='kind',
            field=models.CharField(choices=[('overview', 'Overview'), ('change', 'What changed')], default='overview', max_length=10),
        ),
    ]
